name: 기능 제안
description: 새로운 기능이나 개선 아이디어를 공유해 주세요.
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        좋은 아이디어 감사합니다! 아래 내용을 채워 주시면 검토에 도움이 됩니다.

  - type: textarea
    id: problem
    attributes:
      label: 어떤 불편함이 있었나요?
      description: 이 기능이 필요하게 된 배경이나 문제를 설명해 주세요.
      placeholder: "예: 커밋을 여러 개 한 번에 분석하고 싶은데 현재는 하나씩만 가능합니다."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 원하는 동작
      description: 어떻게 동작하면 좋을 것 같나요?
      placeholder: "예: 최근 N개의 커밋을 선택해 일괄 분석하는 버튼이 있으면 좋겠습니다."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 고려해본 대안 (선택)
      description: 다른 해결 방법을 생각해 보셨나요?

  - type: textarea
    id: extra
    attributes:
      label: 추가 정보 (선택)
      description: 참고할 만한 레퍼런스, 스크린샷, 관련 이슈 등
